MicrosoftSQL:
 connection:
  Host: "![/U3sdk1NYro2Wn4HinU7qD4gQQqmpXS1]"
  Port: "![7CvCwCf/gxU=]"
  User: "![iZxiVbOPMoRZiZUjyEaI5w==]"
  Password: "![8o6hHd9i23Lx1J1GwiIfTw==]"
 

Http:
 connection:
  Host: "![E4GKMUg99Gw=]"
  Port: "![lqWAQ0ZDzPI=]"
 